import Head from 'next/head';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-3xl font-bold text-slate-700'>Hello world</div>
    </>
  );
};

export default Home;
